### ISSUE TITLE
Development.IDE.GHC gets stuck with -- cores 3

### ISSUE THREAD

**Issue by carnotweat** [cdepillabout/stacklock2nix#10]
I even commented out final.ghcid in flake.nix of easy app to see, but it gets to the point of building it , i even checked other flakes , dotnix files in this and root dir , but this is only where i could find it 
Could be other naive issue , silly mistake or an oversight, but i am wondering atm , how to make it work on my machine

**Comment by cdepillabout** [comment]
Could you give a full description of what you're trying to do (exactly what code you're using, exactly what commands you're running), and the exact error you're seeing?

**Comment by carnotweat** [comment]
My bad . I should have mentioned that in first place
To/do , code
- for now app in your repo
- https://github.com/prolic/futr
For when the above builds
Commands - going by README.md here
cd /path/to/myapp- ..easy
nix build - works 
./result/...
someFunc
It's not a dev/shell yet , so stack, cabal, ghci are not in path
nix develop
Stuck at building development.ghcide..
For >36 hrs
Tried it with 1 job and 3 jobs separately 
My system remains frozen for ~72 hrs now
Cancle ( no trace , i can try verbose, but waiting more for it to throw an error , seemed no-go, what if the threads are dead and i simply don't know.( I may be naive here).
Nix -2.11
Os- nixos
Dell optiplex 7080
Cd path / to/ my-app ... advanced
nix-shell has almost worked, except for some network issue for nar ( i ve dealt with it before, i ll fix , try again) and update here.
In any event i need check thread status when build is happening and that need speed up.
I grabage- collected , twice to be sure .So no ram issues on my side

**Comment by cdepillabout** [comment]
I'm still not sure exactly what code you're running, but if you can upload the exact repo to GitHub you're using, I can take a closer look.

If I had to guess, I'd say that something has hung when you're building HLS.  You could try again after commenting out this line:

https://github.com/cdepillabout/stacklock2nix/blob/fa0ba94e1d7971bba8075eed8e9ac521407caad2/my-example-haskell-lib-easy/flake.nix#L72

**Comment by cdepillabout** [comment]
I'm going to go ahead and close this (since my guess is that this is an HLS issue), but if you're still having problems, we can always re-open this issue.
