### ISSUE TITLE
Haddock is not generated.

### ISSUE THREAD

**Issue by junjihashimoto** [cdepillabout/stacklock2nix#36]
A doc derivation of each package does not include haddock.
The command is as below.

> git clone git@github.com:cdepillabout/stacklock2nix.git
> cd my-example-haskell-lib-advanced/
> nix build .#my-example-haskell-app.doc --allow-import-from-derivation

**Comment by cdepillabout** [comment]
My guess is that the problem here is that the Haskell package `my-example-haskell-lib-advanced` only contains an executable, and executables don't generate any Haddocks?

For instance, you can find Haddocks for the `my-example-haskell-lib` library:

```console
$ nix repl
nix-repl> :lf .
Added 15 variables.
nix-repl> :b outputs.nixpkgs.x86_64-linux.my-example-haskell-stacklock.pkgSet.my-example-haskell-lib

This derivation produced the following outputs:
  doc -> /nix/store/r4c0rqsz072gfjmhyh4bpx0l80wra02b-my-example-haskell-lib-0.1.0.0-doc
  out -> /nix/store/4gxwpashc56c14s962rad6wsb8pafc8w-my-example-haskell-lib-0.1.0.0
```

And the `doc` contains files:

```console
$ ls -lah /nix/store/r4c0rqsz072gfjmhyh4bpx0l80wra02b-my-example-haskell-lib-0.1.0.0-doc/share/doc/my-example-haskell-lib-0.1.0.0/html/index.html
```

**Comment by cdepillabout** [comment]
I'm going to go ahead and close this.  I think this problem is just part of how the Haskell infrastructure in Nixpkgs works, and not something stacklock2nix-specific.

Although if my diagnosis is incorrect, please feel free to re-open this issue.
