### ISSUE TITLE
Git dependency in extra-deps doesn't work if specified commit isn't reachable from remote HEAD

### ISSUE THREAD

**Issue by isomorpheme** [cdepillabout/stacklock2nix#38]
For example, having something like:
```yaml
- git: https://github.com/circuithub/ghc-source-gen.git
  commit: 7a6aac047b706508e85ba2054b5bedbecfd7eb7a
```
in `extra-deps` fails with an error like:
```
error: Cannot find Git revision '7a6aac047b706508e85ba2054b5bedbecfd7eb7a' in ref 'refs/heads/master' of repository 'https://github.com/circuithub/ghc-source-gen.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```
I think this is because of this `fetchGit` call: https://github.com/cdepillabout/stacklock2nix/blob/10d531672cada2e02ac49b1b18293e7a94938a38/nix/build-support/stacklock2nix/default.nix#L379-L383

Adding `allRefs = true` as the error suggests would solve this, but there's probably repos where it's much slower to do that, so maybe there's a cleverer solution, or it can just be made configurable?

**Comment by cdepillabout** [comment]
Thanks for submitting this!

I released https://github.com/cdepillabout/stacklock2nix/releases/tag/v4.0.0, which uses your suggested fix from https://github.com/runtimeverification/hs-backend-booster/commit/62139cd3ad35defebed986ad0c169a9a0cf9e4bb.
