### ISSUE TITLE
Failure when 'packages' is missing from stack.yaml

### ISSUE THREAD

**Issue by chris-martin** [cdepillabout/stacklock2nix#49]
`stack.yaml` isn't required to have a `packages` entry.

For example: https://github.com/freckle/stack-lint-extra-deps/blob/933e210e1626128516c3a5f1646b04f04ac122e3/stack.yaml

stacklock2nix doesn't handle this case where it is not present.

```
error:
       … while evaluating the attribute 'packages.x86_64-linux.stack-lint-extra-deps'

         at /nix/store/xlva939kzpr2jmsxppz20mcrm6kb327v-source/flake.nix:57:9:

           56|       packages = forAllSystems (system: {
           57|         stack-lint-extra-deps = nixpkgsFor.${system}.stack-lint-extra-deps;
             |         ^
           58|       });

       … while evaluating the attribute 'x86_64-linux.stack-lint-extra-deps'

         at /nix/store/xlva939kzpr2jmsxppz20mcrm6kb327v-source/flake.nix:95:9:

           94|
           95|         stack-lint-extra-deps =
             |         ^
           96|           final.stack-lint-extra-deps-stacklock.pkgSet.stack-lint-extra-deps;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'packages' missing

       at /nix/store/3v8xdvmxxp3wf1w4m05chih2hyxs00bb-source/nix/build-support/stacklock2nix/default.nix:641:30:

          640|   # localPkgs :: [ { pkgPath :: Path, pkgName :: String } ]
          641|   localPkgs = map mkLocalPkg stackYamlParsed.packages;
             |                              ^
          642|
```

A workaround is to add to `stack.yaml`:

```yaml
packages:
  - .
```

So I suspect the solution is to default the missing attribute value to `[ "." ]`.

**Comment by cdepillabout** [comment]
@chris-martin Thanks for reporting this.  I think this should be fixable.

Just curious, what you are using `stack` / `stack.yaml` for where you don't have any local packages?  I don't think I've seen someone do this before.

**Comment by chris-martin** [comment]
> where you don't have any local packages

There is a local package, it's just that there is only one. If you don't have a `packages` entry in `stack.yaml`, Stack will assume that there is one package and its root is in the same directory as the `stack.yaml` file.

**Comment by cdepillabout** [comment]
Oh nice, didn't realize `packages` worked like this if it is missing.  Let me redo #50 to take this into account.
