### ISSUE TITLE
Github style extra-deps without subdirs broken

### ISSUE THREAD

**Issue by TeofilC** [cdepillabout/stacklock2nix#5]
The issue seems to be that when using a github entry in the extra-deps section, stack saves that as a URL in stack.yaml.lock. It looks like this is only unpacked if the subdirs option is given, but it should alway be unpacked. Otherwise you get an error from cabal2nix, which tries to call nix-prefetch-url but it doesn't have it on its PATH.

I'm not sure if the correct thing to do is always unpack or to use the version of cabal2nix that has nix-prefetch-url on its path. Currently I'm using the former to work around this.

**Comment by cdepillabout** [comment]
> Currently I'm using the former to work around this.

Would you be able to send a PR for this?

It sounds like you might have already figured out it, but I imagine the following code block will need to be fixed:

https://github.com/cdepillabout/stacklock2nix/blob/a00ad2393f9d8a82c94d39b2ac4e0c15c9b89b69/nix/build-support/stacklock2nix/default.nix#L320-L346
