### ISSUE TITLE
Lost in timeouts for libs/18.yaml

### ISSUE THREAD

**Issue by carnotweat** [cdepillabout/stacklock2nix#9]
Even with nix flake check/prefetch my nix-shell does get GHC / nar.xz packages /stack/cabal elsewhere

**Comment by cdepillabout** [comment]
@carnotweat Could you give a better description of what you're trying to do, where you're seeing an error, how someone could reproduce your error, etc?

**Comment by carnotweat** [comment]
That's my bad 
I merely needed to add " ip raw.githu..." to extra hosts in configuration.nix
175th line in 
https://github.com/carnotweat/remoteflake/commit/29583cef13b4a9e8fa2e3e126cfc6d759df41119#
